export const RouteURL = {
  index: "/",
  blogs: "/blogs",
  contact: "/contact",
  privacypolicy: "/privacy-policy",
  services: {
    root: "/services",
    webdev: "/services/website",
    mobiledev: "/services/mobile",
    transformation: "/services/transformation",
    blockchain: "/services/blockchain",
    uiux: "/services/design",
  },
  about: {
    root: "/about",
    leadership: "/about/leadership",
    detailLeadership: "/about/leadership/detail",
  },
  solutions: {
    root: "/solutions",
    erp: "/solutions/erp",
    hris: "/solutions/hris",
    propertyManagement: "/solutions/property-management",
    financeManagement: "/solutions/finance-management",
    wasteManagement: "/solutions/waste-management",
    NFTMarketplace: "/solutions/nft-marketplace",
    ecommerceApp: "/solutions/ecommerce-app",
  },
  industries: {
    root: "/industries",
    oilAndGas: "/industries/oil-and-gas",
    mining: "/industries/mining",
    education: "/industries/education",
    property: "/industries/property",
    automotive: "/industries/automotive",
    healthcare: "/industries/healthcare",
    travelAndHospitality: "/industries/travel-and-hospitality",
    retail: "/industries/retail",
    others: "/industries/others",
  },
};

export const RouteURLExternal = {
  nortisacademy: "https://nortisacademy.id/",
  blog: "https://blog.dot.co.id",
  whatsapp: "http://wa.me/6285795677652",
  mail: "mailto:dearpartner@dot.co.id",
  linkedin: "https://www.linkedin.com/company/dot-indonesia",
  instagram: "https://www.instagram.com/dot.indonesia/",
  youtube: "https://www.youtube.com/channel/UCjY3ThYjMFYmmldE5sZJeLQ",
  dribbble: "https://dribbble.com/dot_indonesia",
  facebook: "https://www.facebook.com/dotindonesia/",
  careers: "https://career.dot.co.id",
  engineering: "https://engineering.dot.co.id/",
  partner: "https://partner.dot.co.id/",
};
